language: python
python: '2.7'
sudo: required
env:
  #matrix:
  - OS_TYPE=centos OS_VERSION=6
  - OS_TYPE=centos OS_VERSION=7
  - OS_TYPE=ubuntu_lts OS_VERSION=12
  - OS_TYPE=ubuntu_lts OS_VERSION=14

branches:
  # blacklist
  except:
    - master
#  only:
#  - ansible_1.9.2

services:
  - docker

script:
  # Run tests
  - tests/runtests.sh ${OS_TYPE} ${OS_VERSION}
#  # Run tests on Ubuntu 12
#  - docker build -t test_weldpua2008/ubuntu_12.04 ubuntu/LTS/12/
#  #;docker run --rm=true test_weldpua2008/ubuntu_12.04 /bin/bash -c "ansible --version"
#  # Run tests on Ubuntu 14
#  - docker build -t test_weldpua2008/ubuntu_14.04 ubuntu/LTS/14/
##  # Run tests on CentOS6
#  - docker build -t test_weldpua2008/centos6 centos/6
##  # Run tests on CentOS7
#  - docker build -t test_weldpua2008/centos7 centos/7
