language: python
python: '2.7'
sudo: required
env:
  #matrix:
  - OS_TYPE=centos OS_VERSION=6
  - OS_TYPE=centos OS_VERSION=7
  - OS_TYPE=ubuntu_lts OS_VERSION=12
  - OS_TYPE=ubuntu_lts OS_VERSION=14
  - OS_TYPE=fedora OS_VERSION=22
  - OS_TYPE=opensuse OS_VERSION=13.2

branches:
  # blacklist
  except:
    - master
#  only:
#  - ansible_1.9.2

services:
  - docker

script:
  # Run tests
  - tests/runtests.sh ${OS_TYPE} ${OS_VERSION}

