language: python
python: '2.7'
sudo: required
env:
  #matrix:
  - OS_TYPE=oraclelinux OS_VERSION=6
  - OS_TYPE=centos OS_VERSION=5
  - OS_TYPE=centos OS_VERSION=6
  - OS_TYPE=centos OS_VERSION=7
  - OS_TYPE=ubuntu_lts OS_VERSION=12
  - OS_TYPE=ubuntu_lts OS_VERSION=14
  - OS_TYPE=ubuntu OS_VERSION=15.04
  - OS_TYPE=ubuntu OS_VERSION=15.10
  - OS_TYPE=fedora OS_VERSION=21
  - OS_TYPE=fedora OS_VERSION=22
  - OS_TYPE=opensuse OS_VERSION=13.2
  - OS_TYPE=alpine OS_VERSION=3.2
  - OS_TYPE=debian OS_VERSION=8
  - OS_TYPE=debian OS_VERSION=7
  - OS_TYPE=gentoo OS_VERSION=stage3-amd64

branches:
  # blacklist
  except:
    - master
#  only:
#  - ansible_1.9.2

services:
  - docker

script:
  # Run tests
  - tests/runtests.sh ${OS_TYPE} ${OS_VERSION}

notifications:
  email: false
